### ISSUE TITLE
Postgresql configuration

### ISSUE THREAD

**Issue by proptrading** [BitcoinExchangeFH/BitcoinExchangeFH#159]
* Bitcoin exchange feedhandler version: dev 1Mar20
* Python version: 3.6
* Operating System: Ubuntu 18

### Description

Could you give a full example of postgresql config for configuration.yaml?

### What I Did

I've try to run 

> bitcoinexchangefh -pg -pgdest "bitcoin:bitcoin@localhost:5432/bcex" -pgschema public -instmts subscription.ini
> Error: no such option: -p

and I've setup my configuration.yaml file with:

> handlers:
>     pg:
>         pgdest: "user:passwd@server:25060/feed?sslmode=require"
>         pgschema: public
>         instmts: "subscription.ini

But no way to make it run.
Thanks

**Comment by gavincyi** [comment]
Now you just need to provide a configuration file by, for example, `bitcoinexchangefh --configuration configuration.yaml`

while the configuration should contain all the connection information

e.g.

```
handlers:
  sql:
        connection: "postgres://admin:donotusethispassword@aws-us-east-1-portal.19.dblayer.com:15813/compose"
        is_rotate: True
        rotate_frequency: "%Y%m%d%H%M"        
```
